# Generated by Django 4.2.4 on 2023-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='credit',
            field=models.CharField(default="NASA's Goddard Space Flight Center", max_length=254),
            preserve_default=False,
        ),
    ]
