# Generated by Django 4.2.4 on 2023-09-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default='https://svs.gsfc.nasa.gov/14225', max_length=254),
            preserve_default=False,
        ),
    ]
